mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('page.urls')),
]

page/urls.py
from django.urls import path

from . import views

app_name = "page" 

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('experiences/', views.experience, name='experience'),
    path('project/', views.project, name='project'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
]

page/models.py
from django.db import models

# Create your models here.

page/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'page/HOME.html')

def aboutme(request):
    return render(request, 'page/ABOUT.html')

def experience(request):
    return render(request, 'page/EXPERIENCES.html')

def project(request):
    return render(request, 'page/PROJECT.html')

def gallery(request):
    return render(request, 'page/GALLERY.html')

def contact(request):
    return render(request, 'page/CONTACT.html')

page/templates/page/ABOUT.html
{% extends "page/BASE.html" %}

{% load static %}
{% block page_content %}
    <div class="photo21"></div>
    <div class="profile1"></div>
    <div class="perkenalan">Hello, I’m Shannia Dwi Melianti and I’m interesting in design and technologies.  </div>
    <div class="education">
            2018 - 2022 <br/>
            Universitas Indonesia<br>
            <br/>
            2015 - 2018<br>
            SMAN 7 Tangerang Selatan          
    </div>
    <div class="header-edu">
    E  D  U <br/>C  A  T<br/>I  O  N
    </div>
    <div class="photo22"></div>
    <div class="profile2"></div>
    <div class="title-page">A B O U T M E</div>
    <div class="style1">A B O U T M E</div>
    <div class="style2">A B O U T M E</div>
    <div class="header-skill">EDUCATION SKILLS</div>

    <div class="container-1">
        <div class="row">
            <div class="col-sm">
                <div class="python"></div>
            </div>
            <div class="col-sm">
                <div class="java"></div>
            </div>
            <div class="col-sm">
                <div class="html"></div>
            </div>
            <div class="col-sm">
                <div class="css"></div>
            </div>
        </div>
    </div>
    
{% endblock %}

page/templates/page/BASE.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <title>SHANS</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <script href="{% static 'js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </head>
<body>

    {% block page_content %}
    {% endblock %}

    <nav class="navbar navbar-expand-md sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'page:home' %}"> SHANS</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#mainNav">
                <span class="navbar-toggler-icon" style="background: black"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainNav">
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item" >
                        <a class="nav-link" href="{% url 'page:aboutme' %}">ABOUT ME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'page:experience' %}">EXPERIENCES</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'page:project' %}" >PROJECT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'page:gallery' %}" >GALLERY</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'page:contact' %}" >CONTACT</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="footer">
        <a class="footer-logo">made by SHANS</a>
    </div>

</body>
</html>

page/templates/page/CONTACT.html
{% extends "page/BASE.html" %}

{% load static %}
{% block page_content %}
    <div class="c-bag-1"></div>
    <div class="c-bag-2"></div>
    <div class="c-bag-3"></div>
    <div class="c-bag-4"></div>
    <div class="judul-contact">
        <div class="con-1">CONTACT</div>
        <div class="con-2">CONTACT</div>
        <div class="con-3">CONTACT</div>
        <div class="con-4">CONTACT</div>
        <div class="con-5">CONTACT</div>
    </div>
    <div class="horizontal"></div>
    <div class="container-2">
        <div class="row">
          <div class="col-sm align-content-center">
              <a class="gmail" href="mailto:shannia.dwim@gmail.com"></a>
          </div>
          <div class="col-sm align-content-center">
              <a class="linkedin" href="https://www.linkedin.com/in/shannia-dwi-melianti-825741159/"></a>
          </div>
          <div class="col-sm align-content-center">
              <a class="instagram" href="https://www.instagram.com/shanniadm/"></a>
          </div>
          <div class="col-sm align-content-center">
              <a class="youtube" href="https://www.youtube.com/channel/UCuX-I38rbM5CzYtNiHU1-Zg/videos?view_as=subscriber"></a>
          </div>
        </div>
      </div>

{% endblock %}

page/templates/page/EXPERIENCES.html
{% extends "page/BASE.html" %}

{% load static %}
{% block page_content %}
    <div class="e-bag-1"></div>
    <div class="e-bag-2"></div>
    <div class="e-bag-3"></div>
    <div class="e-bag-4"></div>

    <div class="ach">
        <div class="e-judul-1">
            <div class="ach-1"> A C H I E V E M E N T S</div>
            <div class="ach-2"> A C H I E V E M E N T S</div>
            <div class="ach-3"> A C H I E V E M E N T S</div>
        </div>  
        <div class="achievements">
            <div class="tahun-ach">2015<br/>2018</div>
            <div class="ach-2015">3rd Place in Jabodetabek<br/>Vocal Grup Competition</div>
            <div class="ach-2018">1st Best Student at Natural Science<br/> Major SMAN 7 Tangerang Selatan</div>
        </div>     
    </div>
    
    <div class="exp">
        <div class="judul-exp">
            <div class="exp-1"> E X P E R I E N C E S</div>
            <div class="exp-2"> E X P E R I E N C E S</div>
            <div class="exp-3"> E X P E R I E N C E S</div>
        </div>
        <div class="experiences">
            <div class="tahun-exp">2016<br/>2019</div>
            <div class="exp-2016">as Secretary <br/>at Voseuth Choir</div>
            <div class="exp-2019">as Decoration Division Staff<br/>at UI Ethnovaganza 2019</div>
        </div>
    </div>
    
{% endblock %}

page/templates/page/GALLERY.html
{% extends "page/BASE.html" %}

{% load static %}
{% block page_content %}
    <div class="bag-1"></div>
    <div class="bag-2"></div>
    <div class="bag-3"></div>
    <div class="bag-4"></div>

    <div class="judul-gal">
        <div class="gal-1"> G A L L E R Y</div>
        <div class="gal-2"> G A L L E R Y</div>
        <div class="gal-3"> G A L L E R Y</div>
    </div> 

    <div class="baris-1">
        <div class="g-photo-1"></div>
        <div class="fyi-1">with Puspa Swara at Tokopedia AI Center<br/>of Excelent Inauguration  2019</div>
        <div class="g-photo-2"></div>
        <div class="fyi-2">with Puspa Swara at Closing DigiTalent<br/>Scholarship 2019</div>
    </div>
{% endblock %}

page/templates/page/HOME.html
{% extends "page/BASE.html" %}

{% load static %}
{% block page_content %}
    <div class="photo1"></div>
    <div class="photo2"></div>
    <div class="photo4"></div>
    <div class="photo3"></div>

    <div class="judulutama">S‏   H‏   A‏   N‏   S</div>

    <div class="quote1">“Art is not a thing, it is the<br/>way of life.” -Elbert Hubbert</div>
    <div class="line1"></div>
    <div class="line2"></div>
    <div class="quote2">Let me take you into my own world <br/>which is beyond your imagination.</div> 

{% endblock %}

page/templates/page/PROJECT.html
{% extends "page/BASE.html" %}

{% load static %}
{% block page_content %}
    <div class="bag-1"></div>
    <div class="bag-2"></div>
    <div class="bag-3"></div>
    <div class="bag-4"></div>
    <div class="judul-project"> ART & MUSIC PROJECT</div>

    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/U7k7ZRTPUpM?rel=0" allowfullscreen></iframe>
    </div>
{% endblock %}